// =========================================================
// NETFLIX MOVIE DATABASE
// =========================================================

const movies = [

    // =====================================================
    // INTERNATIONAL / POPULAR
    // =====================================================

    {
        id: 1,
        title: "Stranger Things",
        trailer: "b9EkMc79ZSU",
        year: "2025",
        rating: "16+",
        score: "8.7",
        quality: "4K Ultra HD",
        seasons: "4 Seasons",
        duration: "50m per ep",
        genre: "Drama",
        cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour"],
        director: "The Duffer Brothers",
        description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
        isNetflixOriginal: true,
        isTrending: true,
        isTop10: true,
        top10Rank: 1
    },

    {
        id: 2,
        title: "Wednesday",
        trailer: "Di310WS8zLk",
        year: "2025",
        rating: "13+",
        score: "8.1",
        quality: "4K Ultra HD",
        seasons: "2 Seasons",
        duration: "45m per ep",
        genre: "Fantasy",
        cast: ["Jenna Ortega", "Gwendoline Christie", "Riki Lindhome", "Christina Ricci"],
        director: "Tim Burton",
        description: "Wednesday Addams investigates mysterious events while navigating life, rivalries and supernatural secrets at Nevermore Academy.",
        isNetflixOriginal: true,
        isTrending: true,
        isTop10: true,
        top10Rank: 2
    },

    {
        id: 3,
        title: "Squid Game",
        trailer: "oqxAJKy0ii4",
        year: "2024",
        rating: "16+",
        score: "8.0",
        quality: "4K Ultra HD",
        seasons: "3 Seasons",
        duration: "55m per ep",
        genre: "Thriller",
        cast: ["Lee Jung-jae", "Park Hae-soo", "Wi Ha-joon", "Hoyeon"],
        director: "Hwang Dong-hyuk",
        description: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games for an alluring high-stakes prize with deadly consequences.",
        isNetflixOriginal: true,
        isTrending: true,
        isTop10: true,
        top10Rank: 3
    },

    {
        id: 4,
        title: "Money Heist",
        trailer: "_InqQJRqGW4",
        year: "2021",
        rating: "16+",
        score: "8.2",
        quality: "HD",
        seasons: "5 Parts",
        duration: "45m per ep",
        genre: "Crime",
        cast: ["Álvaro Morte", "Úrsula Corberó", "Itziar Ituño", "Pedro Alonso"],
        director: "Álex Pina",
        description: "Eight thieves take hostages and lock themselves in the Royal Mint of Spain as a criminal mastermind manipulates the police to carry out his plan.",
        isNetflixOriginal: true,
        isTrending: true,
        isTop10: true,
        top10Rank: 4
    },

    {
        id: 5,
        title: "The Witcher",
        trailer: "ndl1W4ltcmg",
        year: "2023",
        rating: "16+",
        score: "8.1",
        quality: "4K Ultra HD",
        seasons: "3 Seasons",
        duration: "1h per ep",
        genre: "Fantasy",
        cast: ["Henry Cavill", "Anya Chalotra", "Freya Allan", "Joey Batey"],
        director: "Lauren Schmidt Hissrich",
        description: "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
        isNetflixOriginal: true,
        isTrending: true,
        isTop10: true,
        top10Rank: 5
    },

    {
        id: 6,
        title: "Dark",
        trailer: "ESEUoa-mz2c",
        year: "2020",
        rating: "16+",
        score: "8.7",
        quality: "4K Ultra HD",
        seasons: "3 Seasons",
        duration: "50m per ep",
        genre: "Sci-Fi",
        cast: ["Louis Hofmann", "Karoline Eichhorn", "Lisa Vicari", "Oliver Masucci"],
        director: "Baran bo Odar",
        description: "A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery that spans three generations.",
        isNetflixOriginal: true,
        isTrending: false,
        isTop10: true,
        top10Rank: 6
    },

    {
        id: 7,
        title: "The Night Agent",
        trailer: "YDbnY9Obsfs",
        year: "2025",
        rating: "16+",
        score: "7.7",
        quality: "4K Ultra HD",
        seasons: "2 Seasons",
        duration: "45m per ep",
        genre: "Action",
        cast: ["Gabriel Basso", "Luciane Buchanan", "Fola Evans-Akingbola"],
        director: "Shawn Ryan",
        description: "While monitoring an emergency line, a low-level FBI agent answers a call that plunges him into a deadly conspiracy involving a mole at the White House.",
        isNetflixOriginal: true,
        isTrending: true,
        isTop10: true,
        top10Rank: 7
    },

    {
        id: 8,
        title: "The Umbrella Academy",
        trailer: "0DAmWHxeoKw",
        year: "2024",
        rating: "16+",
        score: "7.9",
        quality: "HD",
        seasons: "4 Seasons",
        duration: "50m per ep",
        genre: "Fantasy",
        cast: ["Elliot Page", "Tom Hopper", "David Castañeda", "Emmy Raver-Lampman"],
        director: "Steve Blackman",
        description: "Reunited by their father's death, estranged siblings with extraordinary powers uncover shocking family secrets — and a threat to humanity.",
        isNetflixOriginal: true,
        isTrending: false,
        isTop10: true,
        top10Rank: 8
    },

    {
        id: 9,
        title: "Peaky Blinders",
        trailer: "oVzVdvGIC7U",
        year: "2022",
        rating: "16+",
        score: "8.8",
        quality: "4K Ultra HD",
        seasons: "6 Seasons",
        duration: "55m per ep",
        genre: "Drama",
        cast: ["Cillian Murphy", "Paul Anderson", "Helen McCrory", "Tom Hardy"],
        director: "Steven Knight",
        description: "A notorious gang in 1919 Birmingham, England, is led by the fierce Tommy Shelby, a crime boss set on moving up in the world no matter the cost.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: true,
        top10Rank: 9
    },

    {
        id: 10,
        title: "Bridgerton",
        trailer: "gpv7ayf_tyE",
        year: "2024",
        rating: "13+",
        score: "7.4",
        quality: "4K Ultra HD",
        seasons: "3 Seasons",
        duration: "1h per ep",
        genre: "Romance",
        cast: ["Nicola Coughlan", "Luke Newton", "Jonathan Bailey", "Simone Ashley"],
        director: "Chris Van Dusen",
        description: "The eight close-knit siblings of the Bridgerton family look for love and happiness in London high society, guided by Lady Whistledown's scandalous newsletters.",
        isNetflixOriginal: true,
        isTrending: true,
        isTop10: true,
        top10Rank: 10
    },

    // =====================================================
    // ACTION MOVIES
    // =====================================================

    {
        id: 11,
        title: "Jawan",
        trailer: "COv52Qyctws",
        year: "2023",
        rating: "16+",
        score: "7.5",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 49m",
        genre: "Action",
        cast: ["Shah Rukh Khan", "Nayanthara", "Vijay Sethupathi", "Deepika Padukone"],
        director: "Atlee",
        description: "A high-octane action thriller highlighting the emotional journey of a man who is set to rectify the wrongs in society.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 12,
        title: "Pathaan",
        trailer: "vqu4z34wENw",
        year: "2023",
        rating: "16+",
        score: "6.9",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 26m",
        genre: "Action",
        cast: ["Shah Rukh Khan", "Deepika Padukone", "John Abraham", "Dimple Kapadia"],
        director: "Siddharth Anand",
        description: "An Indian agent races against time to stop a ruthless mercenary with a deadly weapon from attacking his country.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 13,
        title: "Extraction",
        trailer: "L6P3nI6VnlY",
        year: "2020",
        rating: "16+",
        score: "6.8",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "1h 56m",
        genre: "Action",
        cast: ["Chris Hemsworth", "Rudhraksh Jaiswal", "Randeep Hooda", "Golshifteh Farahani"],
        director: "Sam Hargrave",
        description: "A hardened mercenary's mission becomes a soul-searching race to survive when he's sent into Bangladesh to rescue a drug lord's kidnapped son.",
        isNetflixOriginal: true,
        isTrending: true,
        isTop10: false
    },

    {
        id: 14,
        title: "Extraction 2",
        trailer: "Y274jZs5s7s",
        year: "2023",
        rating: "16+",
        score: "7.0",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 02m",
        genre: "Action",
        cast: ["Chris Hemsworth", "Golshifteh Farahani", "Tornike Gogrichiani", "Idris Elba"],
        director: "Sam Hargrave",
        description: "Back from the brink of death, highly skilled commando Tyler Rake embarks on another dangerous mission: saving the imprisoned family of a ruthless gangster.",
        isNetflixOriginal: true,
        isTrending: true,
        isTop10: false
    },

    {
        id: 15,
        title: "Brahmāstra Part One: Shiva",
        trailer: "BUjXzrgntcY",
        year: "2022",
        rating: "13+",
        score: "5.6",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 47m",
        genre: "Fantasy",
        cast: ["Ranbir Kapoor", "Alia Bhatt", "Amitabh Bachchan", "Nagarjuna Akkineni"],
        director: "Ayan Mukerji",
        description: "A DJ with a mysterious connection to fire discovers his destiny as a guardian of ancient weapons and must protect the world from dark forces.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 16,
        title: "RRR",
        trailer: "NgBoMJy386M",
        year: "2022",
        rating: "16+",
        score: "7.8",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "3h 07m",
        genre: "Action",
        cast: ["N.T. Rama Rao Jr.", "Ram Charan", "Ajay Devgn", "Alia Bhatt"],
        director: "S.S. Rajamouli",
        description: "A fearless warrior on a perilous mission comes face to face with a steely cop serving British forces in this epic saga set in pre-independent India.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 17,
        title: "KGF Chapter 2",
        trailer: "JKa05nyUmuQ",
        year: "2022",
        rating: "16+",
        score: "8.3",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 48m",
        genre: "Action",
        cast: ["Yash", "Sanjay Dutt", "Raveena Tandon", "Srinidhi Shetty"],
        director: "Prashanth Neel",
        description: "In the blood-soaked Kolar Gold Fields, Rocky's name strikes fear into his foes. While his allies look up to him, the government sees him as a threat.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 18,
        title: "John Wick",
        trailer: "C0BMx-qxsP4",
        year: "2014",
        rating: "16+",
        score: "7.4",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 41m",
        genre: "Action",
        cast: ["Keanu Reeves", "Michael Nyqvist", "Alfie Allen", "Willem Dafoe"],
        director: "Chad Stahelski",
        description: "An ex-hitman comes out of retirement to track down the gangsters that took everything from him, embarking on an unrelenting rampage.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 19,
        title: "John Wick Chapter 2",
        trailer: "XGk2EfbD_Ps",
        year: "2017",
        rating: "16+",
        score: "7.4",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 02m",
        genre: "Action",
        cast: ["Keanu Reeves", "Riccardo Scamarcio", "Ian McShane", "Common"],
        director: "Chad Stahelski",
        description: "Bound by an unbreakable blood oath, legendary assassin John Wick travels to Rome to square off against the world's deadliest killers.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 20,
        title: "John Wick Chapter 4",
        trailer: "qEVUtrk8_B4",
        year: "2023",
        rating: "16+",
        score: "7.7",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 49m",
        genre: "Action",
        cast: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård", "Laurence Fishburne"],
        director: "Chad Stahelski",
        description: "John Wick uncovers a path to defeating the High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 21,
        title: "Mission Impossible Fallout",
        trailer: "wb49-oV0F78",
        year: "2018",
        rating: "13+",
        score: "7.7",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 27m",
        genre: "Action",
        cast: ["Tom Cruise", "Henry Cavill", "Ving Rhames", "Simon Pegg"],
        director: "Christopher McQuarrie",
        description: "When an IMF mission ends badly, Ethan Hunt and his team must race against time to stop nuclear weapons from falling into the wrong hands.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 22,
        title: "Top Gun Maverick",
        trailer: "giXco2jaZ_4",
        year: "2022",
        rating: "13+",
        score: "8.3",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 11m",
        genre: "Action",
        cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly", "Jon Hamm"],
        director: "Joseph Kosinski",
        description: "After thirty years of service as a top naval aviator, Pete 'Maverick' Mitchell trains a detachment of graduates for a specialized, dangerous mission.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 23,
        title: "The Gray Man",
        trailer: "BmllggGO4pM",
        year: "2022",
        rating: "16+",
        score: "6.5",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 02m",
        genre: "Action",
        cast: ["Ryan Gosling", "Chris Evans", "Ana de Armas", "Dhanush"],
        director: "Anthony Russo, Joe Russo",
        description: "When a shadowy CIA agent uncovers agency secrets, a psychopathic former colleague puts a bounty on his head and sets off a global manhunt.",
        isNetflixOriginal: true,
        isTrending: false,
        isTop10: false
    },

    {
        id: 24,
        title: "Army of the Dead",
        trailer: "tI1JGPhYBS8",
        year: "2021",
        rating: "18+",
        score: "5.8",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 28m",
        genre: "Action",
        cast: ["Dave Bautista", "Ella Purnell", "Omari Hardwick", "Ana de la Reguera"],
        director: "Zack Snyder",
        description: "After a zombie outbreak in Las Vegas, a group of mercenaries takes the ultimate gamble by venturing into the quarantine zone for the greatest heist ever attempted.",
        isNetflixOriginal: true,
        isTrending: false,
        isTop10: false
    },

    {
        id: 25,
        title: "Black Adam",
        trailer: "X0tOpBuYasI",
        year: "2022",
        rating: "13+",
        score: "6.2",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 05m",
        genre: "Action",
        cast: ["Dwayne Johnson", "Aldis Hodge", "Pierce Brosnan", "Noah Centineo"],
        director: "Jaume Collet-Serra",
        description: "Nearly 5,000 years after he was bestowed with the powers of the ancient gods, Black Adam is freed from his earthly tomb to unleash his unique justice.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 26,
        title: "The Batman",
        trailer: "mqqft2x_Aa4",
        year: "2022",
        rating: "13+",
        score: "7.8",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 56m",
        genre: "Action",
        cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano", "Colin Farrell"],
        director: "Matt Reeves",
        description: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 27,
        title: "Aquaman",
        trailer: "WDkg3h8PCVU",
        year: "2018",
        rating: "13+",
        score: "6.8",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 23m",
        genre: "Action",
        cast: ["Jason Momoa", "Amber Heard", "Willem Dafoe", "Patrick Wilson"],
        director: "James Wan",
        description: "Arthur Curry, the human-born heir to the underwater kingdom of Atlantis, goes on a quest to prevent a war between the worlds of ocean and land.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 28,
        title: "Venom",
        trailer: "u9Mv98Gr5pY",
        year: "2018",
        rating: "13+",
        score: "6.6",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 52m",
        genre: "Action",
        cast: ["Tom Hardy", "Michelle Williams", "Riz Ahmed", "Scott Haze"],
        director: "Ruben Fleischer",
        description: "A reporter bounds with an alien symbiote that gives him extraordinary superpowers, turning him into the antihero known as Venom.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 29,
        title: "Black Panther",
        trailer: "xjDjIWPwcPU",
        year: "2018",
        rating: "13+",
        score: "7.3",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 14m",
        genre: "Action",
        cast: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o", "Danai Gurira"],
        director: "Ryan Coogler",
        description: "T'Challa, heir to the hidden Kingdom of Wakanda, must step forward to lead his people into a new era and confront a challenger from his country's past.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 30,
        title: "Avengers Endgame",
        trailer: "TcMBFSGVi1c",
        year: "2019",
        rating: "13+",
        score: "8.4",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "3h 01m",
        genre: "Action",
        cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"],
        director: "Anthony Russo, Joe Russo",
        description: "After devastating events wipe out half the universe, the remaining Avengers assemble once more to reverse Thanos' actions and restore balance.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    // =====================================================
    // COMEDY MOVIES
    // =====================================================

    {
        id: 31,
        title: "The Hangover",
        trailer: "tcdUhdOlz9M",
        year: "2009",
        rating: "18+",
        score: "7.7",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 40m",
        genre: "Comedy",
        cast: ["Bradley Cooper", "Ed Helms", "Zach Galifianakis", "Justin Bartha"],
        director: "Todd Phillips",
        description: "Three buddies wake up from a bachelor party in Las Vegas with no memory of the previous night and the groom missing. They make their way around the city in order to find him.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 32,
        title: "Free Guy",
        trailer: "X2m-08cOAbc",
        year: "2021",
        rating: "13+",
        score: "7.1",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "1h 55m",
        genre: "Comedy",
        cast: ["Ryan Reynolds", "Jodie Comer", "Taika Waititi", "Lil Rel Howery"],
        director: "Shawn Levy",
        description: "A bank teller discovers he is actually a background player in an open-world video game, and decides to become the hero of his own story.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 33,
        title: "Red Notice",
        trailer: "Pj0wz7zu3Ms",
        year: "2021",
        rating: "13+",
        score: "6.3",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "1h 58m",
        genre: "Comedy",
        cast: ["Dwayne Johnson", "Ryan Reynolds", "Gal Gadot", "Ritu Arya"],
        director: "Rawson Marshall Thurber",
        description: "An FBI profiler pursuing the world's most wanted art thief becomes his reluctant partner in crime to catch an elusive criminal who's always one step ahead.",
        isNetflixOriginal: true,
        isTrending: true,
        isTop10: false
    },

    {
        id: 35,
        title: "Game Night",
        trailer: "qmxMAdV6s4U",
        year: "2018",
        rating: "16+",
        score: "7.0",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 40m",
        genre: "Comedy",
        cast: ["Jason Bateman", "Rachel McAdams", "Kyle Chandler", "Sharon Horgan"],
        director: "John Francis Daley, Jonathan Goldstein",
        description: "A group of friends who meet regularly for game nights find themselves entangled in a real-life mystery when the charismatic brother of one of them is kidnapped.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 36,
        title: "We're the Millers",
        trailer: "0Vsy5KzsieQ",
        year: "2013",
        rating: "16+",
        score: "7.0",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 50m",
        genre: "Comedy",
        cast: ["Jennifer Aniston", "Jason Sudeikis", "Emma Roberts", "Will Poulter"],
        director: "Rawson Marshall Thurber",
        description: "A veteran pot dealer creates a fake family as part of his plan to move a huge shipment of weed into the U.S. from Mexico.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 37,
        title: "Jumanji Welcome to the Jungle",
        trailer: "2QKg5SZ_35I",
        year: "2017",
        rating: "13+",
        score: "6.9",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "1h 59m",
        genre: "Comedy",
        cast: ["Dwayne Johnson", "Kevin Hart", "Jack Black", "Karen Gillan"],
        director: "Jake Kasdan",
        description: "Four teenagers are sucked into a magical video game, and the only way they can escape is to work together to finish the game.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 38,
        title: "The Mask",
        trailer: "hOqVRwGVUkA",
        year: "1994",
        rating: "13+",
        score: "6.9",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 41m",
        genre: "Comedy",
        cast: ["Jim Carrey", "Cameron Diaz", "Peter Riegert", "Peter Greene"],
        director: "Chuck Russell",
        description: "Bank clerk Stanley Ipkiss is transformed into a manic superhero when he puts on a mysterious wooden mask.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 42,
        title: "Dumb and Dumber",
        trailer: "l13yPhimE3o",
        year: "1994",
        rating: "13+",
        score: "7.3",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 47m",
        genre: "Comedy",
        cast: ["Jim Carrey", "Jeff Daniels", "Lauren Holly", "Karen Duffy"],
        director: "Peter Farrelly, Bobby Farrelly",
        description: "After a woman leaves a briefcase at the airport, two extremely dim-witted friends go on a cross-country road trip to Aspen to return it.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 44,
        title: "Superbad",
        trailer: "4eaZ_48ZYog",
        year: "2007",
        rating: "16+",
        score: "7.6",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 53m",
        genre: "Comedy",
        cast: ["Jonah Hill", "Michael Cera", "Christopher Mintz-Plasse", "Bill Hader"],
        director: "Greg Mottola",
        description: "Two co-dependent high school seniors deal with separation anxiety after their plan to host a liquor-fueled party goes awry.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 46,
        title: "The Misadventures",
        trailer: "0Vsy5KzsieQ",
        year: "2025",
        rating: "16+",
        score: "6.8",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "1h 45m",
        genre: "Comedy",
        cast: ["Jason Sudeikis", "Kathryn Hahn", "Will Poulter"],
        director: "Rawson Marshall Thurber",
        description: "A group of unlikely companions finds themselves in another chaotic, hilarious road trip filled with unexpected mishaps.",
        isNetflixOriginal: true,
        isTrending: false,
        isTop10: false
    },

    // =====================================================
    // HORROR MOVIES
    // =====================================================

    {
        id: 51,
        title: "The Conjuring",
        trailer: "k10ETZ41q5o",
        year: "2013",
        rating: "16+",
        score: "7.5",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 52m",
        genre: "Horror",
        cast: ["Vera Farmiga", "Patrick Wilson", "Lili Taylor", "Ron Livingston"],
        director: "James Wan",
        description: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 52,
        title: "The Conjuring 2",
        trailer: "VFsmuRPClr4",
        year: "2016",
        rating: "16+",
        score: "7.3",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 14m",
        genre: "Horror",
        cast: ["Vera Farmiga", "Patrick Wilson", "Frances O'Connor", "Madison Wolfe"],
        director: "James Wan",
        description: "Ed and Lorraine Warren travel to North London to help a single mother raising four children alone in a house plagued by malicious spirits.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 53,
        title: "IT",
        trailer: "xKJmEC5ieOk",
        year: "2017",
        rating: "16+",
        score: "7.3",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 15m",
        genre: "Horror",
        cast: ["Bill Skarsgård", "Jaeden Martell", "Finn Wolfhard", "Sophia Lillis"],
        director: "Andy Muschietti",
        description: "In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster, which disguises itself as a clown and preys on children.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 54,
        title: "IT Chapter Two",
        trailer: "bKL1ImsN-DU",
        year: "2019",
        rating: "16+",
        score: "6.5",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 49m",
        genre: "Horror",
        cast: ["Jessica Chastain", "James McAvoy", "Bill Hader", "Bill Skarsgård"],
        director: "Andy Muschietti",
        description: "Twenty-seven years after their first encounter with the terrifying Pennywise, the Losers Club have grown up and moved away, until a devastating phone call brings them back.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 55,
        title: "A Quiet Place",
        trailer: "WR7cc5t7tv8",
        year: "2018",
        rating: "16+",
        score: "7.5",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "1h 30m",
        genre: "Horror",
        cast: ["Emily Blunt", "John Krasinski", "Millicent Simmonds", "Noah Jupe"],
        director: "John Krasinski",
        description: "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 56,
        title: "A Quiet Place Part II",
        trailer: "BpdDN9d9Jio",
        year: "2021",
        rating: "16+",
        score: "7.2",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "1h 37m",
        genre: "Horror",
        cast: ["Emily Blunt", "Cillian Murphy", "Millicent Simmonds", "Noah Jupe"],
        director: "John Krasinski",
        description: "Following the events at home, the Abbott family now face the terrors of the outside world as they continue their fight for survival in silence.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 57,
        title: "Insidious",
        trailer: "zuZnRUcoWos",
        year: "2010",
        rating: "16+",
        score: "6.8",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 43m",
        genre: "Horror",
        cast: ["Patrick Wilson", "Rose Byrne", "Lin Shaye", "Ty Simpkins"],
        director: "James Wan",
        description: "A family looks to prevent evil spirits from trapping their comatose child in a realm called The Further.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 58,
        title: "Insidious Chapter 2",
        trailer: "fBbi4NeebAk",
        year: "2013",
        rating: "16+",
        score: "6.6",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 46m",
        genre: "Horror",
        cast: ["Patrick Wilson", "Rose Byrne", "Barbara Hershey", "Lin Shaye"],
        director: "James Wan",
        description: "The Lamberts attempt to uncover the mysterious childhood secret that has left them dangerously connected to the spirit world.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 60,
        title: "Annabelle Creation",
        trailer: "KisPhy7T__Q",
        year: "2017",
        rating: "16+",
        score: "6.5",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 49m",
        genre: "Horror",
        cast: ["Stephanie Sigman", "Talitha Bateman", "Lulu Wilson", "Anthony LaPaglia"],
        director: "David F. Sandberg",
        description: "12 years after the tragic death of their little girl, a doll-maker and his wife welcome a nun and several girls from a shuttered orphanage into their home.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 61,
        title: "The Nun",
        trailer: "pzD9zGcUNrw",
        year: "2018",
        rating: "16+",
        score: "5.3",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 36m",
        genre: "Horror",
        cast: ["Demián Bichir", "Taissa Farmiga", "Jonas Bloquet", "Bonnie Aarons"],
        director: "Corin Hardy",
        description: "A priest with a haunted past and a novice on the threshold of her final vows are sent by the Vatican to investigate the death of a young nun in Romania.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 62,
        title: "The Nun II",
        trailer: "QF-oyCwaArU",
        year: "2023",
        rating: "16+",
        score: "5.6",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "1h 50m",
        genre: "Horror",
        cast: ["Taissa Farmiga", "Jonas Bloquet", "Storm Reid", "Anna Popplewell"],
        director: "Michael Chaves",
        description: "1956 – France. A priest is murdered. An evil is spreading. The sequel to the worldwide smash hit follows Sister Irene as she once again comes face-to-face with Valak.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 63,
        title: "Smile",
        trailer: "BcDK7lkzzsU",
        year: "2022",
        rating: "16+",
        score: "6.5",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "1h 55m",
        genre: "Horror",
        cast: ["Sosie Bacon", "Jessie T. Usher", "Kyle Gallner", "Kal Penn"],
        director: "Parker Finn",
        description: "After witnessing a bizarre, traumatic incident involving a patient, a psychiatrist starts experiencing terrifying occurrences that she can't explain.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 64,
        title: "Smile 2",
        trailer: "0HY6QFlBzUY",
        year: "2024",
        rating: "16+",
        score: "7.1",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 07m",
        genre: "Horror",
        cast: ["Naomi Scott", "Rosemarie DeWitt", "Lukas Gage", "Miles Gutierrez-Riley"],
        director: "Parker Finn",
        description: "About to embark on a new world tour, global pop sensation Skye Riley begins experiencing increasingly terrifying and inexplicable events.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 66,
        title: "Scream VI",
        trailer: "h74AXqw4Opc",
        year: "2023",
        rating: "16+",
        score: "6.5",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 02m",
        genre: "Horror",
        cast: ["Melissa Barrera", "Jenna Ortega", "Courteney Cox", "Jasmin Savoy Brown"],
        director: "Matt Bettinelli-Olpin, Tyler Gillett",
        description: "In the next installment, the survivors of the Ghostface killings leave Woodsboro behind and start a fresh chapter in New York City.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 67,
        title: "The Exorcist",
        trailer: "BU2eYAO31Cc",
        year: "1973",
        rating: "18+",
        score: "8.1",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 02m",
        genre: "Horror",
        cast: ["Ellen Burstyn", "Max von Sydow", "Linda Blair", "Lee J. Cobb"],
        director: "William Friedkin",
        description: "When a 12-year-old girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her daughter.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 68,
        title: "The Ring",
        trailer: "yzR2GY-ew8I",
        year: "2002",
        rating: "16+",
        score: "7.1",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 55m",
        genre: "Horror",
        cast: ["Naomi Watts", "Martin Henderson", "Brian Cox", "David Dorfman"],
        director: "Gore Verbinski",
        description: "A journalist must investigate a mysterious videotape which seems to cause the death of anyone within a week of viewing it.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 69,
        title: "The Grudge",
        trailer: "O2NKzO-fxwQ",
        year: "2004",
        rating: "16+",
        score: "5.9",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 31m",
        genre: "Horror",
        cast: ["Sarah Michelle Gellar", "Jason Behr", "Clea DuVall", "William Mapother"],
        director: "Takashi Shimizu",
        description: "An American nurse living and working in Tokyo is exposed to a mysterious supernatural curse, one that locks a person in a powerful rage.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    // =====================================================
    // ROMANCE MOVIES
    // =====================================================

    {
        id: 71,
        title: "The Notebook",
        trailer: "FC6biTjEyZw",
        year: "2004",
        rating: "13+",
        score: "7.8",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 03m",
        genre: "Romance",
        cast: ["Ryan Gosling", "Rachel McAdams", "James Garner", "Gena Rowlands"],
        director: "Nick Cassavetes",
        description: "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom, but they are soon separated because of their social differences.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 72,
        title: "Me Before You",
        trailer: "Eh993__rOxA",
        year: "2016",
        rating: "13+",
        score: "7.4",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 50m",
        genre: "Romance",
        cast: ["Emilia Clarke", "Sam Claflin", "Janet McTeer", "Charles Dance"],
        director: "Thea Sharrock",
        description: "A girl in a small town forms an unlikely bond with a recently-paralyzed man she's taking care of, changing both of their lives forever.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 73,
        title: "La La Land",
        trailer: "0pdqf4P9MB8",
        year: "2016",
        rating: "13+",
        score: "8.0",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 08m",
        genre: "Romance",
        cast: ["Ryan Gosling", "Emma Stone", "John Legend", "Rosemarie DeWitt"],
        director: "Damien Chazelle",
        description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 74,
        title: "Titanic",
        trailer: "kVrqfYjkTdQ",
        year: "1997",
        rating: "13+",
        score: "7.9",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "3h 14m",
        genre: "Romance",
        cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates"],
        director: "James Cameron",
        description: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 75,
        title: "To All the Boys I've Loved Before",
        trailer: "555oiY9RWM4",
        year: "2018",
        rating: "13+",
        score: "7.0",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 39m",
        genre: "Romance",
        cast: ["Lana Condor", "Noah Centineo", "Janel Parrish", "Anna Cathcart"],
        director: "Susan Johnson",
        description: "A teenage girl's secret love letters are exposed and wreak havoc on her love life when they are mysteriously mailed to all five of her crushes.",
        isNetflixOriginal: true,
        isTrending: false,
        isTop10: false
    },

    {
        id: 76,
        title: "The Fault in Our Stars",
        trailer: "9ItBvH5J6ss",
        year: "2014",
        rating: "13+",
        score: "7.7",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 06m",
        genre: "Romance",
        cast: ["Shailene Woodley", "Ansel Elgort", "Nat Wolff", "Laura Dern"],
        director: "Josh Boone",
        description: "Two teenage cancer patients begin a life-affirming journey to visit a reclusive author in Amsterdam.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 77,
        title: "Crazy Rich Asians",
        trailer: "ZQ-YX-5bAs0",
        year: "2018",
        rating: "13+",
        score: "6.9",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 0m",
        genre: "Romance",
        cast: ["Constance Wu", "Henry Golding", "Michelle Yeoh", "Gemma Chan"],
        director: "Jon M. Chu",
        description: "This contemporary romantic comedy follows native New Yorker Rachel Chu as she accompanies her longtime boyfriend to his best friend's wedding in Singapore.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 80,
        title: "Love Actually",
        trailer: "KdzH6a-XEGM",
        year: "2003",
        rating: "13+",
        score: "7.6",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 15m",
        genre: "Romance",
        cast: ["Hugh Grant", "Martine McCutcheon", "Liam Neeson", "Colin Firth"],
        director: "Richard Curtis",
        description: "Follows the lives of eight very different couples in dealing with their love lives in various loosely interrelated tales all set during a frantic month before Christmas.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    // =====================================================
    // DRAMA MOVIES
    // =====================================================

    {
        id: 81,
        title: "The Shawshank Redemption",
        trailer: "PLl99DlL6b4",
        year: "1994",
        rating: "16+",
        score: "9.3",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 22m",
        genre: "Drama",
        cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
        director: "Frank Darabont",
        description: "Over the course of several years, two convicts form a friendship, seeking consolation and eventual redemption through basic compassion.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 82,
        title: "Forrest Gump",
        trailer: "bLvqoHBptjg",
        year: "1994",
        rating: "13+",
        score: "8.8",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 22m",
        genre: "Drama",
        cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
        director: "Robert Zemeckis",
        description: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 83,
        title: "The Pursuit of Happyness",
        trailer: "DMOBlEcRuw8",
        year: "2006",
        rating: "13+",
        score: "8.0",
        quality: "HD",
        seasons: "Movie",
        duration: "1h 57m",
        genre: "Drama",
        cast: ["Will Smith", "Jaden Smith", "Thandiwe Newton", "Brian Howe"],
        director: "Gabriele Muccino",
        description: "A struggling salesman takes custody of his son as he's poised to begin a life-changing professional endeavor.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 84,
        title: "The Social Network",
        trailer: "lB95KLmpLR4",
        year: "2010",
        rating: "13+",
        score: "7.8",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 0m",
        genre: "Drama",
        cast: ["Jesse Eisenberg", "Andrew Garfield", "Justin Timberlake", "Armie Hammer"],
        director: "David Fincher",
        description: "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 85,
        title: "Whiplash",
        trailer: "7d_jQycdQGo",
        year: "2014",
        rating: "16+",
        score: "8.5",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "1h 47m",
        genre: "Drama",
        cast: ["Miles Teller", "J.K. Simmons", "Paul Reiser", "Melissa Benoist"],
        director: "Damien Chazelle",
        description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 86,
        title: "The Green Mile",
        trailer: "Ki4haFrqSrw",
        year: "1999",
        rating: "16+",
        score: "8.6",
        quality: "HD",
        seasons: "Movie",
        duration: "3h 09m",
        genre: "Drama",
        cast: ["Tom Hanks", "Michael Clarke Duncan", "David Morse", "Bonnie Hunt"],
        director: "Frank Darabont",
        description: "A tale set on death row in a Southern prison, where a gentle giant accused of a child murder displays extraordinary healing powers.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 87,
        title: "Good Will Hunting",
        trailer: "PaZVjZEFkRs",
        year: "1997",
        rating: "16+",
        score: "8.3",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 06m",
        genre: "Drama",
        cast: ["Robin Williams", "Matt Damon", "Ben Affleck", "Stellan Skarsgård"],
        director: "Gus Van Sant",
        description: "Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 88,
        title: "The Wolf of Wall Street",
        trailer: "iszwuX1AK6A",
        year: "2013",
        rating: "18+",
        score: "8.2",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "3h 0m",
        genre: "Drama",
        cast: ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie", "Matthew McConaughey"],
        director: "Martin Scorsese",
        description: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 89,
        title: "Oppenheimer",
        trailer: "uYPbbksJxIg",
        year: "2023",
        rating: "16+",
        score: "8.9",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "3h 0m",
        genre: "Drama",
        cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
        director: "Christopher Nolan",
        description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 90,
        title: "The Revenant",
        trailer: "LoebZZ8K5N0",
        year: "2015",
        rating: "16+",
        score: "8.0",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 36m",
        genre: "Drama",
        cast: ["Leonardo DiCaprio", "Tom Hardy", "Domhnall Gleeson", "Will Poulter"],
        director: "Alejandro G. Iñárritu",
        description: "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    // =====================================================
    // INDIAN / BOLLYWOOD MOVIES
    // =====================================================

    {
        id: 91,
        title: "Dangal",
        trailer: "x_7YlGv9u1g",
        year: "2016",
        rating: "13+",
        score: "8.3",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 41m",
        genre: "Drama",
        cast: ["Aamir Khan", "Sakshi Tanwar", "Fatima Sana Shaikh", "Sanya Malhotra"],
        director: "Nitesh Tiwari",
        description: "Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 92,
        title: "3 Idiots",
        trailer: "K0eDlFX9GMc",
        year: "2009",
        rating: "13+",
        score: "8.4",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 50m",
        genre: "Comedy",
        cast: ["Aamir Khan", "Madhavan", "Mona Singh", "Sharman Joshi", "Kareena Kapoor"],
        director: "Rajkumar Hirani",
        description: "Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 93,
        title: "PK",
        trailer: "SOXWc32k4tA",
        year: "2014",
        rating: "13+",
        score: "8.1",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 33m",
        genre: "Comedy",
        cast: ["Aamir Khan", "Anushka Sharma", "Sushant Singh Rajput", "Sanjay Dutt"],
        director: "Rajkumar Hirani",
        description: "An alien on Earth loses the remote control to his spaceship. His innocent questions and childlike curiosity challenge humanity's blind beliefs.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 94,
        title: "Zindagi Na Milegi Dobara",
        trailer: "FJrpcDgC3zU",
        year: "2011",
        rating: "13+",
        score: "8.2",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 35m",
        genre: "Romance",
        cast: ["Hrithik Roshan", "Farhan Akhtar", "Abhay Deol", "Katrina Kaif", "Kalki Koechlin"],
        director: "Zoya Akhtar",
        description: "Three friends decide to turn their fantasy vacation into reality after one of them becomes engaged, discovering love and overcoming fears across Spain.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 95,
        title: "Kabir Singh",
        trailer: "RiANSSgCuJk",
        year: "2019",
        rating: "18+",
        score: "7.0",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 53m",
        genre: "Romance",
        cast: ["Shahid Kapoor", "Kiara Advani", "Arjan Bajwa", "Suresh Oberoi"],
        director: "Sandeep Reddy Vanga",
        description: "Kabir Singh, a senior medical student with anger management issues, goes on a self-destructive path after his girlfriend is forced to marry someone else.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 96,
        title: "Drishyam",
        trailer: "64xJLmcA2K8",
        year: "2015",
        rating: "13+",
        score: "8.2",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 43m",
        genre: "Thriller",
        cast: ["Ajay Devgn", "Shriya Saran", "Tabu", "Rajat Kapoor"],
        director: "Nishikant Kamat",
        description: "Desperate measures are taken by a man who tries to save his family from the dark side of the law after they commit an unexpected crime.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 97,
        title: "Stree 2",
        trailer: "VlvOgk5BHS4",
        year: "2024",
        rating: "16+",
        score: "7.6",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 27m",
        genre: "Horror",
        cast: ["Rajkummar Rao", "Shraddha Kapoor", "Pankaj Tripathi", "Abhishek Banerjee"],
        director: "Amar Kaushik",
        description: "The town of Chanderi is haunted once again, this time by a headless entity known as Sarkata. The townspeople turn to Vicky and his friends for protection.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 98,
        title: "Bhool Bhulaiyaa",
        trailer: "GGzSId0_qJc",
        year: "2007",
        rating: "13+",
        score: "7.4",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 39m",
        genre: "Horror",
        cast: ["Akshay Kumar", "Vidya Balan", "Shiney Ahuja", "Amisha Patel"],
        director: "Priyadarshan",
        description: "An NRI and his wife decide to stay in his ancestral home, paying no heed to warnings about ghosts. Soon, inexplicable occurrences cause them to call a psychiatrist.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 99,
        title: "Chhichhore",
        trailer: "tsxemFX0a7k",
        year: "2019",
        rating: "13+",
        score: "8.3",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 23m",
        genre: "Drama",
        cast: ["Sushant Singh Rajput", "Shraddha Kapoor", "Varun Sharma", "Prateik Babbar"],
        director: "Nitesh Tiwari",
        description: "A tragic incident forces Anirudh, a middle-aged man, to take a trip down memory lane and reminisce his college days along with his friends, who were labelled losers.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 100,
        title: "Taare Zameen Par",
        trailer: "GGzSId0_qJc",
        year: "2007",
        rating: "7+",
        score: "8.3",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 45m",
        genre: "Drama",
        cast: ["Aamir Khan", "Darsheel Safary", "Tisca Chopra", "Vipin Sharma"],
        director: "Aamir Khan",
        description: "An 8-year-old boy is thought to be a lazy trouble-maker, until the new art teacher has the patience and compassion to discover the real problem behind his struggles in school.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 101,
        title: "Om Shanti Om",
        trailer: "9oeGoQGt7Ao",
        year: "2007",
        rating: "13+",
        score: "8.0",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 49m",
        genre: "Romance",
        cast: ["Shah Rukh Khan", "Deepika Padukone", "Arjun Rampal", "Kirron Kher"],
        director: "Farah Khan",
        description: "In the 1970s, Om, a junior artist, is murdered while attempting to save his love Shanti. Reincarnated in the 2000s, he seeks revenge and redemption.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 102,
        title: "Dhoom 3",
        trailer: "yeF_b8EQcK0",
        year: "2013",
        rating: "13+",
        score: "5.4",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 52m",
        genre: "Action",
        cast: ["Aamir Khan", "Katrina Kaif", "Abhishek Bachchan", "Uday Chopra"],
        director: "Vijay Krishna Acharya",
        description: "When Sahir, a circus entertainer trained in magic and acrobatics, turns into a thief to take down a corrupt bank in Chicago, two Indian cops are called in.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 104,
        title: "Sultan",
        trailer: "wPxqcq6Byq0",
        year: "2016",
        rating: "13+",
        score: "7.0",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 50m",
        genre: "Drama",
        cast: ["Salman Khan", "Anushka Sharma", "Randeep Hooda", "Amit Sadh"],
        director: "Ali Abbas Zafar",
        description: "Sultan is a classic underdog story about a wrestler's journey, looking for a comeback by defeating all odds staked against him.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 105,
        title: "Tiger Zinda Hai",
        trailer: "ePO5M5DE01I",
        year: "2017",
        rating: "16+",
        score: "5.9",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 41m",
        genre: "Action",
        cast: ["Salman Khan", "Katrina Kaif", "Sajjad Delafrooz", "Paresh Rawal"],
        director: "Ali Abbas Zafar",
        description: "Inspired by real events, Tiger Zinda Hai is a sequel to the blockbuster Ek Tha Tiger, following two secret agents on a daring rescue mission.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 106,
        title: "Raees",
        trailer: "J7_1MU3gDk0",
        year: "2017",
        rating: "16+",
        score: "6.8",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 23m",
        genre: "Crime",
        cast: ["Shah Rukh Khan", "Nawazuddin Siddiqui", "Mahira Khan", "Mohammed Zeeshan Ayyub"],
        director: "Rahul Dholakia",
        description: "A bootlegger sets out to improve his community as a promising leader but encounters a tough, unyielding cop who threatens to dismantle his empire.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 107,
        title: "Chennai Express",
        trailer: "hZGR5Sj1Bfo",
        year: "2013",
        rating: "13+",
        score: "6.1",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 21m",
        genre: "Comedy",
        cast: ["Shah Rukh Khan", "Deepika Padukone", "Sathyaraj", "Nikitin Dheer"],
        director: "Rohit Shetty",
        description: "A man heading towards Rameshwaram to immerse his late grandfather's ashes accidentally boards a train that leads him straight into South Indian mob territory.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 108,
        title: "Barfi!",
        trailer: "rVpPO9xuwVY",
        year: "2012",
        rating: "13+",
        score: "8.1",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 31m",
        genre: "Romance",
        cast: ["Ranbir Kapoor", "Priyanka Chopra", "Ileana D'Cruz", "Saurabh Shukla"],
        director: "Anurag Basu",
        description: "Set in the 1970s in a charming corner of India, Barfi! is the story of three young people who learn that love can neither be defined nor contained by society's norms.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 109,
        title: "Yeh Jawaani Hai Deewani",
        trailer: "aG5oOFAO9yc",
        year: "2013",
        rating: "13+",
        score: "7.2",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 40m",
        genre: "Romance",
        cast: ["Ranbir Kapoor", "Deepika Padukone", "Aditya Roy Kapur", "Kalki Koechlin"],
        director: "Ayan Mukerji",
        description: "Kabir and Naina bond during a trekking trip. Before Naina can express her feelings, Kabir leaves to pursue his career. Years later, they meet again at a friend's wedding.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 113,
        title: "Bajrangi Bhaijaan",
        trailer: "74z6rvKLPP0",
        year: "2015",
        rating: "13+",
        score: "8.1",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 39m",
        genre: "Drama",
        cast: ["Salman Khan", "Harshaali Malhotra", "Nawazuddin Siddiqui", "Kareena Kapoor"],
        director: "Kabir Khan",
        description: "An Indian man with a magnanimous heart takes a young mute Pakistani girl back to her homeland to reunite her with her family.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    },

    {
        id: 114,
        title: "Kick",
        trailer: "u-j1nx_HY5o",
        year: "2014",
        rating: "13+",
        score: "5.4",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 26m",
        genre: "Action",
        cast: ["Salman Khan", "Jacqueline Fernandez", "Nawazuddin Siddiqui", "Randeep Hooda"],
        director: "Sajid Nadiadwala",
        description: "An adrenaline junkie breaks up with his girlfriend and embarks on a daring life of crime as a masked thief, pursued by a cop.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 119,
        title: "Krrish",
        trailer: "yj4bnTrqwvA",
        year: "2006",
        rating: "13+",
        score: "6.4",
        quality: "HD",
        seasons: "Movie",
        duration: "2h 55m",
        genre: "Action",
        cast: ["Hrithik Roshan", "Priyanka Chopra", "Rekha", "Naseeruddin Shah"],
        director: "Rakesh Roshan",
        description: "Krishna is born with magical powers - a legacy inherited from his father. He must conceal his abilities until he falls in love with Priya and travels to Singapore.",
        isNetflixOriginal: false,
        isTrending: false,
        isTop10: false
    },

    {
        id: 120,
        title: "Shaitaan",
        trailer: "A_HQdwRDRrw",
        year: "2024",
        rating: "16+",
        score: "6.7",
        quality: "4K Ultra HD",
        seasons: "Movie",
        duration: "2h 12m",
        genre: "Horror",
        cast: ["Ajay Devgn", "R. Madhavan", "Jyotika", "Janki Bodiwala"],
        director: "Vikas Bahl",
        description: "A family's weekend retreat turns into a living nightmare when a mysterious stranger enters their home and hypnotizes their young daughter.",
        isNetflixOriginal: false,
        isTrending: true,
        isTop10: false
    }

];

// =========================================================
// GENERATE POSTERS AND BACKDROPS FROM YOUTUBE TRAILERS
// =========================================================

movies.forEach(movie => {
    // Primary thumbnail image
    movie.image = `https://img.youtube.com/vi/${movie.trailer}/hqdefault.jpg`;
    // High-resolution backdrop image
    movie.backdrop = `https://img.youtube.com/vi/${movie.trailer}/maxresdefault.jpg`;
});

// =========================================================
// HELPER UTILITIES
// =========================================================

function getMovieById(id) {
    const numId = Number(id);
    return movies.find(m => m.id === numId) || null;
}

function getMoviesByGenre(genreName) {
    if (!genreName || genreName === "All") return movies;
    return movies.filter(m => m.genre && m.genre.toLowerCase() === genreName.toLowerCase());
}

function getTop10Movies() {
    return movies.filter(m => m.isTop10).sort((a, b) => (a.top10Rank || 99) - (b.top10Rank || 99));
}

function getTrendingMovies() {
    return movies.filter(m => m.isTrending);
}

// Make accessible to non-module scripts if needed
if (typeof window !== 'undefined') {
    window.movies = movies;
    window.getMovieById = getMovieById;
    window.getMoviesByGenre = getMoviesByGenre;
    window.getTop10Movies = getTop10Movies;
    window.getTrendingMovies = getTrendingMovies;
}